//
// CountryNameNativeNameValue.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct CountryNameNativeNameValue: Codable, Hashable {

    public var official: String?
    public var common: String?

    public init(official: String? = nil, common: String? = nil) {
        self.official = official
        self.common = common
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case official
        case common
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(official, forKey: .official)
        try container.encodeIfPresent(common, forKey: .common)
    }
}

