//
// CountryDemonymsValue.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct CountryDemonymsValue: Codable, Hashable {

    public var f: String?
    public var m: String?

    public init(f: String? = nil, m: String? = nil) {
        self.f = f
        self.m = m
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case f
        case m
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(f, forKey: .f)
        try container.encodeIfPresent(m, forKey: .m)
    }
}

