//
// CountryFlags.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct CountryFlags: Codable, Hashable {

    /** URL флага в формате PNG. */
    public var png: String?
    /** URL флага в формате SVG. */
    public var svg: String?

    public init(png: String? = nil, svg: String? = nil) {
        self.png = png
        self.svg = svg
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case png
        case svg
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(png, forKey: .png)
        try container.encodeIfPresent(svg, forKey: .svg)
    }
}

